version: '3'

services:
  database:
    image: postgres:11.4
    container_name: reddit_db
    volumes:
       - ${POSTGRES_VOLUME}:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "5435:5432"

  app:
    build: .
    container_name: reddit_app
    links:
      - database
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=development
      - APP_DATABASE_URI=postgresql+psycopg2://${POSTGRES_USER}:${POSTGRES_PASSWORD}@reddit_db:5432/${POSTGRES_DB}
    depends_on:
      - database
    ports:
      - "5000:5000"
