version: '3'

services:
  database:
    image: postgres:11.4
    container_name: reddit_db
    volumes:
       - ${POSTGRES_VOLUME}:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - ${POSTGRES_PORT}:5432

  app:
    build: .
    container_name: reddit_app
    links:
      - database
      - object_cache
      - list_cache
      - event_queue
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=development
      - POSTGRES_HOST=reddit_db
      - POSTGRES_PORT=5432
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - OBJECT_CACHE_HOST=reddit_object_cache
      - OBJECT_CACHE_PORT=6379
      - LIST_CACHE_HOST=reddit_list_cache
      - LIST_CACHE_PORT=6380
      - RABBITMQ_HOST=reddit_queue
      - RABBITMQ_PORT=5672
    depends_on:
      - database
      - object_cache
      - list_cache
      - event_queue
    ports:
      - 5000:5000

  object_cache:
    image: redis
    container_name: reddit_object_cache
    expose:
      - 6379
    ports:
      - ${OBJECT_CACHE_PORT}:6379

  list_cache:
    image: redis
    container_name: reddit_list_cache
    expose:
      - 6380
    ports:
      - ${LIST_CACHE_PORT}:6380

  event_queue:
    image: rabbitmq:3-management
    container_name: reddit_queue
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}
    expose:
      - 5672
    ports:
      - ${RABBITMQ_PORT}:5672
      - 15672:15672
