"""empty message

Revision ID: 090619455ee1
Revises: 4c59f0747bd4
Create Date: 2020-02-28 14:51:43.010627

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '090619455ee1'
down_revision = '4c59f0747bd4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('thread', 'random_new_field')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('thread', sa.Column('random_new_field', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
