"""empty message

Revision ID: 4c59f0747bd4
Revises: 4b160fda8e28
Create Date: 2020-02-28 14:49:02.339648

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4c59f0747bd4'
down_revision = '4b160fda8e28'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('thread', sa.Column('random_new_field', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('thread', 'random_new_field')
    # ### end Alembic commands ###
